version: '3'

services:
    r1ng-backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: yarn start
        environment:
            RDB_HOST: "r1ng-database"
            RDB_PORT: "3306"
            RDB_USER: "root"
            RDB_PASSWORD: "password"
            RDB_DATABASE: "r1ng"
        ports:
            - "24001:24001"
        volumes:
            - ./src:/opt/r1ng/src
        depends_on:
            - "r1ng-database"
        networks:
            - "r1ng-local-network"

    r1ng-database:
        image: mysql:8.0.19
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'r1ng'
        ports:
            - "24002:3306"
        networks:
            - "r1ng-local-network"

networks:
    r1ng-local-network:
        external:
            name: "r1ng-local-network"
