version: '3'

services:
    fp-backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: yarn watch
        environment:
            RDB_HOST: "fp-database"
            RDB_PORT: "3306"
            RDB_USER: "root"
            RDB_PASSWORD: "password"
            RDB_DATABASE: "fp"
            RDB_POOL_MIN: "0"
            RDB_POOL_MAX: "10"
        ports:
            - "24001:24001"
        volumes:
            - ./src:/opt/r1ng/src
        depends_on:
            - "fp-database"
        networks:
            - "fp-local-network"

    fp-database:
        image: mysql:8.0.19
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: "password"
            MYSQL_DATABASE: 'fp'
        ports:
            - "24002:3306"
        networks:
            - "fp-local-network"

networks:
    fp-local-network:
        external:
            name: "fp-local-network"
